### ISSUE TITLE
Circular dependency causing failed import

### ISSUE THREAD

**Issue by PureTryOut** [nxp-mcuxpresso/spsdk#55]
Using spsdk 1.10.0:

```
======================================================================
ERROR: spsdk.dat (unittest.loader._FailedTest.spsdk.dat)
----------------------------------------------------------------------
ImportError: Failed to import test module: spsdk.dat
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 440, in _find_test_path
    package = self._get_module_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/dat/__init__.py", line 9, in <module>
    from .dac_packet import DebugAuthenticationChallenge
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/dat/dac_packet.py", line 12, in <module>
    from spsdk.dat.debug_credential import DebugCredential
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/dat/debug_credential.py", line 16, in <module>
    from spsdk.crypto.signature_provider import SignatureProvider, get_signature_provider
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/crypto/signature_provider.py", line 23, in <module>
    from spsdk.utils.crypto.backend_internal import internal_backend
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/utils/crypto/__init__.py", line 25, in <module>
    from .cert_blocks import CertBlock, CertBlockV2, CertBlockV31
  File "/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/utils/crypto/cert_blocks.py", line 23, in <module>
    from spsdk.crypto.signature_provider import SignatureProvider, get_signature_provider
ImportError: cannot import name 'SignatureProvider' from partially initialized module 'spsdk.crypto.signature_provider' (most likely due to a circular import) (/home/bart/Documents/Git/alpine/aports/testing/py3-spsdk/src/spsdk-1.10.0/spsdk/crypto/signature_provider.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by BohdanMarek** [comment]
Hi,

First of all, thank you for your contribution 💪

I have analyzed the problem and found the root cause of the issue.

In the first place, I looked at the way how to prevent this situation in the future. Our tests did not find this problem due to the way how Python import system works and caches the imported modules. I tested also circular import checker such as _pycycle_ with no success. 

We will closely look at the way how to better test circular imports problems. 

I have implemented a hotfix which will be released in 1.10.1. This will contain a fix of the circular import issue keeping the backwards compatibility.
We are also planning to do a big redesign of the crypto backend modules in 1.11 release, so also signature provider will be refactored.

I will keep you informed about the progress

**Comment by BohdanMarek** [comment]
Hi @PureTryOut ,
As mentioned in my previous comment. The hotfix has been implemented and released to Github.
Let me know once you test it. :)

**Comment by PureTryOut** [comment]
For reference, https://github.com/nxp-mcuxpresso/spsdk/commit/bae3d35c008d9534710454232059f1fc2ed7ec84 is the hotfix mentioned (it would've been nice to have referenced this issue in the commit message :sweat_smile:). It does indeed fix the problem, thanks! I've backported it to the package in the Alpine Linux repositories :+1:
